src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\BaseTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 */
class Document
{

    use BaseTrait {
        BaseTrait::__construct as baseConstruct;
    }



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\RealEstate", inversedBy="documents", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $real_estate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filePath;

    /**
     * @ORM\Column(type="integer")
     */
    private $document_type;

    /**
     * @ORM\Column(type="string")
     */
    private $document_mime_type;

    /**
     * @ORM\Column(type="boolean", nullable=false, )
     */
    private $admin_exclusive;

    /**
     * Document constructor.
     */
    public function __construct()
    {
        $this->admin_exclusive = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRealEstate(): ?RealEstate
    {
        return $this->real_estate;
    }

    public function setRealEstate(?RealEstate $real_estate): self
    {
        $this->real_estate = $real_estate;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDocumentType(): ?int
    {
        return $this->document_type;
    }

    public function setDocumentType(int $document_type): self
    {
        $this->document_type = $document_type;

        return $this;
    }

    /**
     * @return string
     */
    public function getFilePath(): string
    {
        return $this->filePath;
    }

    /**
     * @param string $filePath
     */
    public function setFilePath($filePath): void
    {
        $this->filePath = $filePath;
    }

    /**
     * @return mixed
     */
    public function getDocumentMimeType()
    {
        return $this->document_mime_type;
    }

    /**
     * @param mixed $document_mime_type
     */
    public function setDocumentMimeType($document_mime_type): void
    {
        $this->document_mime_type = $document_mime_type;
    }

    /**
     * @return int
     */
    public function getAdminExclusive(): int
    {
        return $this->admin_exclusive;
    }

    /**
     * @param int $admin_exclusive
     */
    public function setAdminExclusive(int $admin_exclusive): void
    {
        $this->admin_exclusive = $admin_exclusive;
    }
}

src/Form/Backend/AgentPageLocalizationType.php
<?php


namespace App\Form\Backend;


use App\Entity\AgentPageLocalization;
use App\Entity\Language;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentPageLocalizationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("language", EntityType::class, array(
            'class' => Language::class,
            'choice_label' => 'name',
            'label' => ''
        ))
            ->add("title", TextType::class, array(
                'required' => true
            ))
            ->add("slug", TextType::class, array(
                'required' => true
            ))
            ->add("content", TextareaType::class, array(
            'required' => true
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => AgentPageLocalization::class,
        ));
    }

}

src/Form/Backend/AgentPageType.php
<?php

namespace App\Form\Backend;

use App\Entity\AgentPage;
use App\Entity\User;
use App\GlobalSettings;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class AgentPageType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("user", EntityType::class, array(
                'class' => User::class,
                'choice_label' => function(User $user){
                    return $user->getFirstName() . " " . $user->getLastName();
                },
                'query_builder' => function (UserRepository $ur) {
                    return $ur->createQueryBuilder('u')
                        ->andWhere("u.roles LIKE '%EMPLOYEE%'");
                },
            ))
            ->add('image_file', VichImageType::class, array(
                'required' => false,
                'download_label' => '',
                'allow_delete' => true,
                'delete_label' => 'izbrisi'))
            ->add("agentPageLocalizations", CollectionType::class, array(
                'entry_type' => AgentPageLocalizationType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => AgentPage::class,
            'locale' => []
        ));
    }

}

src/Form/Backend/BlogCategoryLocalizationType.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 1/14/2020
 * Time: 12:52 PM
 */

namespace App\Form\Backend;


use App\Entity\BlogCategoryLocalization;
use App\Entity\Language;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class BlogCategoryLocalizationType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("language", EntityType::class, array(
        'class' => Language::class,
        'choice_label' => 'name',
        'label' => ''
    ))
            ->add("name", TextType::class, array(
                'required' => true
            ))
            ->add("slug", TextType::class, array(
                'required' => true
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => BlogCategoryLocalization::class,
        ));
    }
}

src/Form/Backend/BlogCategoryType.php
<?php
// src/Form/UserType.php
namespace App\Form\Backend;

use App\Entity\BlogCategory;
use App\Entity\Feature;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BlogCategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("blogcategoryLocalizations", CollectionType::class, array(
            'entry_type' => BlogCategoryLocalizationType::class,
            'entry_options' => [
                'label' => false
            ],
            'by_reference' => false
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => BlogCategory::class,
            'locale' => []
        ));
    }
}

src/Form/Backend/CallButtonType.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 9/27/2018
 * Time: 11:40 AM
 */

namespace App\Form\Backend;


use App\Entity\CallButton;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CallButtonType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("number", TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CallButton::class,
            'locale' => ''
        ));
    }
}

src/Form/Backend/ClientEditType.php
<?php
// src/Form/UserType.php
namespace App\Form\Backend;

use App\Entity\Language;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Enum\RoleEnum;

class ClientEditType extends AbstractType
{
    function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->user = $tokenStorage->getToken()->getUser();
    }


    private $user;

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username', TextType::class)
            ->add('first_name', TextType::class)
            ->add('last_name', TextType::class)
            ->add('phone_no', TelType::class)
            ->add('mobile_phone_number', TelType::class, array(
                "required"=>false
            ))
            ->add('fax_number', TextType::class, array(
                "required"=>false
            ))
            ->add('personal_identification_number', TextType::class, array(
                "required"=>false
            ))
            ->add('company_name', TextType::class, array(
                "required"=>false
            ))
            ->add("userContacts", CollectionType::class, array(
                "entry_type" => UserContactType::class,
                "allow_add" => true,
                "allow_delete" => true,
                "entry_options" => [
                    "label" => false
                ],
                "by_reference" => false
            ))
            ->add("emailLanguage", EntityType::class, array(
                'class' => Language::class,
                'choice_label' => function(Language $language){
                    return $language->getName();
                }
            ));


    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
        ));
    }
}

src/Form/Backend/ClientType.php
<?php
// src/Form/UserType.php
namespace App\Form\Backend;

use App\Entity\Language;
use App\Entity\Location;
use App\Entity\LocationLocalization;
use App\Entity\User;
use App\GlobalSettings;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ClientType extends AbstractType
{
    function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->user = $tokenStorage->getToken()->getUser();
    }


    private $user;

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username', TextType::class)
            ->add('first_name', TextType::class)
            ->add('last_name', TextType::class)
            ->add('phone_no', TelType::class)
            ->add('mobile_phone_number', TelType::class, array(
                "required"=>false
            ))
            ->add('fax_number', TextType::class, array(
                "required"=>false
            ))
            ->add('personal_identification_number', TextType::class, array(
                "required"=>false
            ))
            ->add('company_name', TextType::class, array(
                "required"=>false
            ))
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options' => array('label' => 'Password'),
                'second_options' => array('label' => 'Repeat Password'),
            ))
            ->add("userContacts", CollectionType::class, array(
                "entry_type" => UserContactType::class,
                "allow_add" => true,
                "allow_delete" => true,
                "entry_options" => [
                    "label" => false
                ],
                "by_reference" => false
            ))
            ->add("emailLanguage", EntityType::class, array(
                'class' => Language::class,
                'choice_label' => function(Language $language){
                    return $language->getName();
                }
            ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
            'locale' => []
        ));
    }
}

src/Form/Backend/CmsPageAllMetaType.php
<?php
// This form is used to get all metaLocalization data for one CmsPage
namespace App\Form\Backend;

use App\Entity\CmsPage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CmsPageAllMetaType extends AbstractType
{

    protected $translator;

    function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("cover_photo", PhotoMedataType::class, array(
                "required" => false
            ))
            ->add("cmsPageMetaLocalizations", CollectionType::class, array(
            'entry_type' => CmsPageMetaLocalizationType::class,
            'entry_options' => [
                'label' => false
            ],
            'by_reference' => false
        ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CmsPage::class,
            'locale' => []
        ));
    }
}

src/Form/Backend/CmsPageLocalizationType.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 1/14/2020
 * Time: 12:52 PM
 */

namespace App\Form\Backend;


use App\Entity\CmsPageLocalization;
use App\Entity\Language;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CmsPageLocalizationType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("language", EntityType::class, array(
        'class' => Language::class,
        'choice_label' => 'name',
        'label' => ''
    ))
            ->add("slug", TextType::class, array(
                'required' => true
            ))
            ->add("title", TextType::class, array(
                'required' => true
            ))
            ->add("content", TextareaType::class, array(
                'required' => false
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CmsPageLocalization::class,
        ));
    }
}

src/Form/Backend/DataTransformer/UserSelect2DataTransformer.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 7/14/2020
 * Time: 12:31 PM
 */

namespace App\Form\Backend\DataTransformer;


use Tetranz\Select2EntityBundle\Form\DataTransformer\EntitiesToPropertyTransformer;

class UserSelect2DataTransformer extends EntitiesToPropertyTransformer
{
    public function transform($entities)
    {
        if (empty($entities)) {
            return array();
        }

        $data = array();

        foreach ($entities as $entity) {
            $data[$entity->getId()] = $entity->getFirstName() . ' '. $entity->getLastName();
        }

        return $data;
    }
}

templates/backend/include/alerts.html.twig
<!-- Nav Item - Alerts -->
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">{% if notifications is defined and notifications is not empty %} {{ notifications|length }} {% endif %}</span>
    </a>
    <!-- Dropdown - Alerts -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
         aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
            Upozorenja
        </h6>
        {% if notifications is defined and notifications is not empty %}
        {% for notification in notifications %}
        <a class="dropdown-item d-flex align-items-center" href="{{ path("notification", {"id": notification.id}) }}">
            <div class="mr-3">
                <div class="icon-circle bg-warning">
                    <i class="fas fa-exclamation-triangle text-white"></i>
                </div>
            </div>
            <div>
                <div class="small text-gray-500"><i
                            class="fa fa-cog"></i> {{ notification.getCreatedAt|date("d.m.Y g:ia") }}</div>
                <div>{{ notification.getTriggeredBy().username ~ " " ~ notification.verb|trans }}
                    {% if notification.getObject() is not null %}
                        {{ notification.getObject().getRealEstateLocalizations()|filter(v=> v.language.code == app.request.locale)|first.title }}
                    {% elseif notification.getRealEstateCustomPage() is not null %}
                        {{ notification.getRealEstateCustomPage().getRealEstateCustomPageLocalizations()|filter(v=> v.language.code == app.request.locale)|first.title }}
                    {% endif %}

                </div>
                Neki dodatak

            </div>
        </a>

        {% endfor %}
        {% endif %}
    </div>
</li>

templates/backend/include/base_client_sidebar.html.twig
{% import 'backend/macros/macros.html.twig' as macro %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <a href="{{ path("backend_client_index") }}"><img src="/frontend/img/TD_logo_2-white.svg" style="margin:20px;"></a>


    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Frontend -->
    {{ macro.link( 'index' ,  "Frontend"|trans, "fas fa-fw fa-home" ) }}

    <!-- Nav Item - RealEstate -->
    {{ macro.link( 'client_realestate_list' ,  "Moje nekretnine"|trans, "fas fa-fw fa-building" ) }}

    <!-- Nav Item - RealEstate -->
    {{ macro.link( 'client_realestate_new' ,  "Nova nekretnina"|trans, "fas fa-fw fa-plus" ) }}

    <!-- Nav Item - RealEstate -->
    {{ macro.link( 'client_user_favorite_overview',  "Spremljene nekretnine" | trans, "fas fa-bookmark" ) }}

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

templates/backend/include/base_sidebar.html.twig
{% import 'backend/macros/macros.html.twig' as macro %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <a href="{{ path("backend_index") }}"><img src="/frontend/img/TD_logo_2-white.svg" style="margin:20px;"></a>


    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    {{ macro.link( 'backend_index' ,  "Statistika"|trans, "fas fa-fw fa-tachometer-alt" ) }}

    <!-- Nav Item - User Analytics -->
    {{ macro.link( 'online_users' ,  "Analiza korisnika"|trans, "fas fa-fw fa-users" ) }}

    <!-- Nav Item - Frontend -->
    {{ macro.link( 'index' ,  "Frontend"|trans, "fas fa-fw fa-home" ) }}

    <!-- Nav Item - Users -->
    {{ macro.link( 'user_list' ,  "Zaposlenici"|trans, "fas fa-fw fa-users" ) }}

    <!-- Nav Item - Users -->
    {{ macro.link( 'client_list' ,  "Klijenti"|trans, "fas fa-fw fa-users" ) }}

    <!-- Nav Item - Agents -->
    {{ macro.link( 'agentpage_list' ,  "Stranice Agenata"|trans, "fas fa-fw fa-user-tie" ) }}

    <!-- Nav Item - CmsPage -->
    {{ macro.link( 'cmspage_list' ,  "Blog"|trans, "fas fa-fw fa-edit" ) }}

    <!-- Nav Item - CmsPage -->
    {{ macro.link( 'predefinedcms_list' ,  "Sadržaj"|trans, "fas fa-fw fa-edit" ) }}

    <!-- Nav Item - RealEstate -->
    {{ macro.link( 'realestate_list' ,  "Nekretnine"|trans, "fas fa-fw fa-building" ) }}

    {% if app.user.roles[0] == "ROLE_ADMIN" %}
    <!-- Nav Item - RealEstate -->
    {{ macro.link( 'realestate_invalidated' ,  "Izbrisane nekretnine"|trans, "fas fa-fw fa-building" ) }}
    {% endif %}

    <!-- Nav Item - RealEstateCustomPage -->
    {{ macro.link( 'realestatecustompage_list' ,  "Kategorijske stranice" | trans, "fas fa-fw fa-shower" ) }}

    <!-- Nav Item - CallButton -->
    {{ macro.link( 'callbutton_list' ,  "Call Button"|trans, "fas fa-fw fa-phone" ) }}
    <!-- Nav Item - RealEstateCustomPage -->
    {{ macro.link( 'marketingemail_list' , "Marketing" | trans, "fas fa-fw fa-envelope" ) }}

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Refernce tables -->
    {{ macro.linkWithSumbenuStart( '' ,  "Referentne tablice"|trans, "fas fa-fw fa-database", "refrenceTables" ) }}
    {{ macro.subLink('region_list','Regije') }}
    {{ macro.subLink('feature_list','Značajke') }}
    {{ macro.subLink('location_list','Lokacije') }}
    {{ macro.subLink('blogcategory_list','Kategorije bloga') }}
    {{ macro.subLink('exchangerate_list','Tečajna lista') }}
    {{ macro.subLink('immobilien_test','ImmoScout24 Test') }}
    {{ macro.linkWithSumbenuEnd() }}

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

templates/backend/include/flashnotice.html.twig
{% if type == "error" %}
{% set type = "danger" %}
{% endif %}
<div class="flash-notice">
    <div class="alert alert-{{type}} alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {% if type == "danger" %}<strong>{{ "Greška"|trans }}</strong> {% endif %}{{ message|raw }}.
    </div>
</div>

templates/backend/include/ground_plan.html.twig
{% if gp.mimeType == "application/pdf" %}
    <embed name="plugin" src="{{ gp.filePath }}"  type="application/pdf">
{% else %}
    <img src="{{ gp.filePath }}" alt="">
{% endif %}
<a class="remove-image image-action" onclick="removeGroundPlan('{{gp.uuid}}', {{ gp.id}})">
    <i class="fa fa-trash"></i>
</a>
<a class="unremove-image image-action" onclick="unRemoveGroundPlan('{{gp.uuid}}')">
    <i class="fa fa-trash-restore"></i>
</a>
{% if isNew == true %}
    <input type="hidden" class="gallery-image-id" name="plans_add[]" value="{{gp.id}}">
{% endif %}
{% if isDeleted is defined and isDeleted == true %}
    <input type="hidden" class="gallery-image-id image-remove" name="plans_remove[]" value="{{gp.id}}">
{% endif %}

templates/backend/include/real_estate_single_document.html.twig
<div class="col-lg-3 col-md-4 col-6" >
    <a href="{{ doc.filePath }}" >
        {% if doc.documentMimeType == "application/pdf" %}
            <img style="height: 120px;" src="https://cdn3.iconfinder.com/data/icons/online-learning-basic-lineal/512/09_PDF_File-512.png" />
        {% elseif doc.documentMimeType == "application/msword" %}
            <img style="height: 120px;" src="https://lh4.googleusercontent.com/proxy/-Ttypn68WlN1kA5QFwW77R8gvUHvUfpuqxSn1UazzdFP4Ocl7CYm0TT5YNz7m9XnbROfhTAs672NsWMlA4Gt04nnVtCM5_3y0IdvkqqRdguqi5ClKhEg58-8" />
        {% elseif doc.documentMimeType == "application/vnd.ms-excel" %}
            <img style="height: 120px;" src="https://cdn.iconscout.com/icon/free/png-256/microsoft-excel-3-599366.png" />
        {% else %}
            <img style="height: 120px;" src="https://cdn0.iconfinder.com/data/icons/thin-files-documents/57/thin-069_file_document_doc_word-512.png" />
        {% endif %}
        <p>{{ doc.name }}</p>
    </a>
    {% if app.user.roles[0] == "ROLE_ADMIN" and doc.documentType == 0 %}
        <div class="make-exclusive-button" style="position:absolute;top: 0;right: 0" onclick="markAsExclusive({{doc.id}})">
            <i class="fa fas fa-key" style="font-size: 1.4rem;{% if doc.adminExclusive %}color:yellow;{% endif %}"></i>
        </div>
    {% endif %}
</div>

templates/backend/include/single_real_estate_image.html.twig
<div class="col-lg-3 col-md-4 col-6" style="min-height: 220px;" id="image_id_{{ rei.id }}">
    <a href="{{ rei.path }}">
        <span style="display: inline-block;vertical-align: middle;text-align: center;">&nbsp;</span>
        <img style="vertical-align: middle" class="img-fluid img-thumbnail" src="{{rei.path}}" alt="">
    </a>
    <div class="remove-button" style="position:absolute;top: 0;right: 0" onclick="removeImage({{rei.getId()}})">
        <i class="fa fas fa-times-circle" style="color: red;font-size: 1.4rem"></i>
    </div>

    <div class="star-cover-button" style="position:absolute;top: 1.8rem;right: 0" onclick="setCoverImage({{rei.getId()}})">
        <i class="fa fas fa-star" style="font-size: 1.4rem;{% if rei.isCover() %}color:yellow;{% endif %}"></i>
    </div>
</div>

templates/backend/include/single_real_estate_image2.html.twig
<img src="{{ rei.path }}" alt="">
<a class="remove-image image-action" onclick="removeImage('{{rei.uuid}}', {{ rei.id}})">
    <i class="fa fa-trash"></i>
</a>
<a class="unremove-image image-action" onclick="unRemoveImage('{{rei.uuid}}')">
    <i class="fa fa-trash-restore"></i>
</a>
<a class="mark-featured image-action" data-property-id="0" onclick="setCoverImage('{{rei.uuid}}', {{ rei.id}})">
    <i class="fa fa-star">
    </i>
</a>
{% if isNew == true %}
    <input type="hidden" class="gallery-image-id" name="images_add[]" value="{{rei.id}}">
{% endif %}
{% if isDeleted is defined and isDeleted == true %}
    <input type="hidden" class="gallery-image-id image-remove" name="images_remove[]" value="{{rei.id}}">
{% endif %}