src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AcmeAssert;
use App\Entity\Traits\BaseTrait;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{

    use BaseTrait {
        BaseTrait::__construct as baseConstruct;
    }

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    public $username;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\Length(min="8", minMessage="Lozinka mora sadržavati najmanje {{ limit }} karaktera!")
     * @AcmeAssert\AllowedPassword
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone_no;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $mobile_phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fax_number;

    /**
     * @ORM\Column(type="string", length=11, nullable=true)
     * @Assert\Length(
     *      min = 11,
     *      max = 11,
     *      minMessage = "OIB mora imati točno 11 znakova",
     *      maxMessage = "OIB mora imati točno 11 znakova"
     * )
     */
    private $personal_identification_number;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_code;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserSearch", mappedBy="user", orphanRemoval=true)
     */
    private $userSearches;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RealEstate", mappedBy="agent")
     */
    private $realEstates;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\AgentPage", mappedBy="user", cascade={"persist", "remove"})
     */
    private $agentPage;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="for_user")
     */
    private $notifications;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RealEstate", mappedBy="client")
     */
    private $clientRealEstates;

    /**
     * @ORM\OneToMany(targetEntity=App\Entity\UserFavorite::class, mappedBy="user", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $userFavorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserContact", mappedBy="user", orphanRemoval=true, cascade={"persist"})
     */
    private $userContacts;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserPreference", mappedBy="user", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $userPreference;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language")
     * @ORM\JoinColumn(nullable=true)
     */
    private $emailLanguage;

    /**
     * @ORM\OneToMany(targetEntity=Visit::class, mappedBy="user")
     */
    private $visits;

    /**
     * @ORM\ManyToMany(targetEntity=MarketingEmail::class, mappedBy="sentTo")
     */
    private $marketingEmails;


    public function __construct()
    {
        $this->baseConstruct();
        $this->isActive = true;
        $this->userSearches = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->clientRealEstates = new ArrayCollection();
        $this->userFavorites = new ArrayCollection();
        $this->userContacts = new ArrayCollection();
        $this->visits = new ArrayCollection();
        $this->marketingEmails = new ArrayCollection();

    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
        return $this;
    }


    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function isActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
        return $this;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
        return $this;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    public function setRoles($roles)
    {
        $this->roles = implode(";", $roles);

        return $this;
    }

    public function getRoles()
    {
        return explode(";", $this->roles);
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addConstraint(new UniqueEntity(array(
                "fields" => "email",
                "message" => "Ovaj email se već koristi!")
        ));
        $metadata->addConstraint(new UniqueEntity(array(
                "fields" => "username",
                "message" => "Ovo korisničko ime se već koristi!")
        ));
    }


    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoneNo(): ?string
    {
        return $this->phone_no;
    }

    public function setPhoneNo(string $phone_no): self
    {
        $this->phone_no = $phone_no;

        return $this;
    }

    public function getPersonalIdentificationNumber(): ?string
    {
        return $this->personal_identification_number;
    }

    public function setPersonalIdentificationNumber(?string $personal_identification_number): self
    {
        $this->personal_identification_number = $personal_identification_number;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMobilePhoneNumber()
    {
        return $this->mobile_phone_number;
    }

    /**
     * @return mixed
     */
    public function getFaxNumber()
    {
        return $this->fax_number;
    }

    /**
     * @return mixed
     */
    public function getRealEstates()
    {
        return $this->realEstates;
    }


    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getActivationCode(): ?string
    {
        return $this->activation_code;
    }

    public function setActivationCode(string $activation_code): self
    {
        $this->activation_code = $activation_code;

        return $this;
    }

    /**
     * @return Collection|UserSearch[]
     */
    public function getUserSearches(): Collection
    {
        return $this->userSearches;
    }

    public function addUserSearch(UserSearch $userSearch): self
    {
        if (!$this->userSearches->contains($userSearch)) {
            $this->userSearches[] = $userSearch;
            $userSearch->setUser($this);
        }

        return $this;
    }

    public function removeUserSearch(UserSearch $userSearch): self
    {
        if ($this->userSearches->contains($userSearch)) {
            $this->userSearches->removeElement($userSearch);
            // set the owning side to null (unless already changed)
            if ($userSearch->getUser() === $this) {
                $userSearch->setUser(null);
            }
        }

        return $this;
    }

    public function getAgentPage(): ?AgentPage
    {
        return $this->agentPage;
    }

    public function setAgentPage(AgentPage $agentPage): self
    {
        $this->agentPage = $agentPage;

        // set the owning side of the relation if necessary
        if ($agentPage->getUser() !== $this) {
            $agentPage->setUser($this);
        }
        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {

src/Form/Backend/AgentPageLocalizationType.php
<?php


namespace App\Form\Backend;


use App\Entity\AgentPageLocalization;
use App\Entity\Language;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentPageLocalizationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("language", EntityType::class, array(
            'class' => Language::class,
            'choice_label' => 'name',
            'label' => ''
        ))
            ->add("title", TextType::class, array(
                'required' => true
            ))
            ->add("slug", TextType::class, array(
                'required' => true
            ))
            ->add("content", TextareaType::class, array(
            'required' => true
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => AgentPageLocalization::class,
        ));
    }

}

src/Form/Backend/AgentPageType.php
<?php

namespace App\Form\Backend;

use App\Entity\AgentPage;
use App\Entity\User;
use App\GlobalSettings;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class AgentPageType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("user", EntityType::class, array(
                'class' => User::class,
                'choice_label' => function(User $user){
                    return $user->getFirstName() . " " . $user->getLastName();
                },
                'query_builder' => function (UserRepository $ur) {
                    return $ur->createQueryBuilder('u')
                        ->andWhere("u.roles LIKE '%EMPLOYEE%'");
                },
            ))
            ->add('image_file', VichImageType::class, array(
                'required' => false,
                'download_label' => '',
                'allow_delete' => true,
                'delete_label' => 'izbrisi'))
            ->add("agentPageLocalizations", CollectionType::class, array(
                'entry_type' => AgentPageLocalizationType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => AgentPage::class,
            'locale' => []
        ));
    }

}

src/Form/Backend/BlogCategoryLocalizationType.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 1/14/2020
 * Time: 12:52 PM
 */

namespace App\Form\Backend;


use App\Entity\BlogCategoryLocalization;
use App\Entity\Language;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class BlogCategoryLocalizationType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("language", EntityType::class, array(
        'class' => Language::class,
        'choice_label' => 'name',
        'label' => ''
    ))
            ->add("name", TextType::class, array(
                'required' => true
            ))
            ->add("slug", TextType::class, array(
                'required' => true
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => BlogCategoryLocalization::class,
        ));
    }
}

src/Form/Backend/BlogCategoryType.php
<?php
// src/Form/UserType.php
namespace App\Form\Backend;

use App\Entity\BlogCategory;
use App\Entity\Feature;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BlogCategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("blogcategoryLocalizations", CollectionType::class, array(
            'entry_type' => BlogCategoryLocalizationType::class,
            'entry_options' => [
                'label' => false
            ],
            'by_reference' => false
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => BlogCategory::class,
            'locale' => []
        ));
    }
}

src/Form/Backend/CallButtonType.php
<?php
/**
 * Created by PhpStorm.
 * User: mijatra
 * Date: 9/27/2018
 * Time: 11:40 AM
 */

namespace App\Form\Backend;


use App\Entity\CallButton;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CallButtonType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("number", TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CallButton::class,
            'locale' => ''
        ));
    }
}

src/Form/Backend/CmsPageAllMetaType.php
<?php
// This form is used to get all metaLocalization data for one CmsPage
namespace App\Form\Backend;

use App\Entity\CmsPage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CmsPageAllMetaType extends AbstractType
{

    protected $translator;

    function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("cover_photo", PhotoMedataType::class, array(
                "required" => false
            ))
            ->add("cmsPageMetaLocalizations", CollectionType::class, array(
            'entry_type' => CmsPageMetaLocalizationType::class,
            'entry_options' => [
                'label' => false
            ],
            'by_reference' => false
        ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CmsPage::class,
            'locale' => []
        ));
    }
}

templates/backend/agentpage_list.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Stranice agenata" | trans }}{% endblock %}


{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-6">
                    <h6 class="m-0 font-weight-bold text-primary">{{ "Agenti" | trans }} </h6>
                </div>
                <div class="col-6 text-right">
                    {{ macro.addButton("agentpage_new") }}
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable no-footer dtr-inline" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>{{ "Id"|trans }}</th>
                            <th>{{ "Ime"|trans }}</th>
                            <th>{{ "Prezime"|trans }}</th>
                            <th>{{ "Telefon"|trans }}</th>
                            <th>{{ "Opcije"|trans }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for agentPage in agentpageList %}
                        <tr>
                            <td>
                                {{ agentPage.id }}
                            </td>
                            <td>
                                {{ agentPage.user.firstName }}
                            </td>
                            <td>
                                {{ agentPage.user.lastName }}
                            </td>
                            <td>
                                {{ agentPage.user.phoneNo }}
                            </td>
                            <td>
                                {{ macro.editButton( 'agentpage_edit', agentPage.id) }}
                                {{ macro.deleteButton( 'agentpage_delete', agentPage.id) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script src="{{ asset('backend/js/dataTableDefault.js') }}"></script>
{% endblock %}

templates/backend/blogcategory_list.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Kategorije bloga"|trans }}{% endblock %}


{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-6">
                    <h6 class="m-0 font-weight-bold text-primary">{{ "Kategorije bloga"|trans }} </h6>
                </div>
                <div class="col-6 text-right">
                    {{ macro.addButton("blogcategory_new") }}
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable no-footer dtr-inline" id="dataTable"
                       width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th >{{ "Naziv"|trans }}</th>
                        <th >{{ "Slug"|trans }}</th>
                        <th >{{ "Opcije"|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for blogcategory in blogcategoryList %}
                        {% set localizedPage =  blogcategory.getBlogCategoryLocalizations()|filter(v=> v.language.code == app.request.locale)|first %}
                        <tr>
                            <td>
                                {% if localizedPage.name is defined %}{{ localizedPage.name }}{% endif %}
                            </td>
                            <td>
                                {% if localizedPage.slug is defined %}{{ localizedPage.slug }}{% endif %}
                            </td>
                            <td>
                                {{ macro.editButton( 'blogcategory_edit', blogcategory.id) }}
                                {{ macro.deleteButton( 'blogcategory_delete', blogcategory.id) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script src="{{ asset('backend/js/dataTableDefault.js') }}"></script>
{% endblock %}

templates/backend/feature_list.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Značajke" | trans }}{% endblock %}


{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-6">
                    <h6 class="m-0 font-weight-bold text-primary">{{ "Značajke" | trans }} </h6>
                </div>
                <div class="col-6 text-right">
                    {{ macro.addButton("feature_new") }}
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable no-footer dtr-inline" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th rowspan="1" colspan="3" class="text-center">
                                {{ "Naziv" | trans }}
                            </th>
                            <th rowspan="2" colspan="1">
                                {{ "Opcije" | trans }}
                            </th>
                        </tr>
                        <tr>
                            <th>{{ "Hrvatski" | trans }}</th>
                            <th>{{ "Engleski" | trans }}</th>
                            <th>{{ "Njemački" | trans }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for feature in featureList %}
                        <tr>
                            {% for featureLoco in feature.getFeatureLocalizations() %}
                                <td>
                                    {{ featureLoco.name }}
                                </td>
                            {% endfor %}
                            <td>
                                {{ macro.editButton( 'feature_edit', feature.id) }}
                                {{ macro.deleteButton( 'feature_delete', feature.id) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script src="{{ asset('backend/js/dataTableDefault.js') }}"></script>
{% endblock %}

templates/backend/new_status.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Novi status"|trans }}{% endblock %}

{% block content %}
    {{ macro.containerStart('Novi status') }}
    <div class="col-sm-12 col-lg-6" id="new_status">
        {{ form_start(form, {'attr': {'id': 'frmStatus'}}) }}

        {% include "shared/form_validation_alert.html.twig" %}

        <!-- field roles -->
        <div class="form-group">
            <label for="tblStatusLocalizations">Naziv</label>
            <table class="table" id="tblStatusLocalizations">
                <tbody>
                {% for statusLoco in form.statusLocalizations %}
                    <tr>
                        <td>{{ form_widget(statusLoco.language, { 'attr': {'class': 'form-control'} }) }}</td>
                        <td>{{ form_widget(statusLoco.name, { 'attr': {'class': 'form-control'} }) }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-dark">{{ "Spremi"|trans }}</button>
        </div>

        {{ form_row(form._token) }}

        {{ form_end(form, {'render_rest': false}) }}

    </div>

    {{ macro.containerEnd() }}

{% endblock %}

templates/backend/realestatecustompage_list.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Kategorijske stranice" | trans }}{% endblock %}


{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-6">
                    <h6 class="m-0 font-weight-bold text-primary">{{ "Kategorijske stranice" | trans }} </h6>
                </div>
                <div class="col-6 text-right">
                    {{ macro.addButton("realestatecustompage_new") }}
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable no-footer dtr-inline" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>{{ "Naziv" | trans }}</th>
                        <th>{{ "Slug" | trans }}</th>
                        <th>{{ "Naziv nadkategorije" | trans }}</th>
                        <th>{{ "Aktivna" | trans }}</th>
                        <th>{{ "Opcije" | trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for recp in realestatecustompageList %}
                        {% set recpLoco = recp.getRealEstateCustomPageLocalization(app.request.locale) %}
                        <tr>
                            <td>{{ recpLoco.title }}</td>
                            <td>{{ recpLoco.slug }}</td>
                            <td>
                                {% set parentRecp = recp.getParentRealEstateCustomPage() %}
                                {% if parentRecp is not null %}
                                    {{ parentRecp.getRealEstateCustomPageLocalization(app.request.locale).title }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>
                                {% if recp.active == true %}
                                    {{ "DA" | trans }}
                                {% else %}
                                    {{ "NE" | trans }}
                                {% endif %}
                            </td>
                            <td>
                                {{ macro.editButton( 'realestatecustompage_edit', recp.id) }}
                                {{ macro.editMetaButton( 'realestatecustompagemeta_edit', recp.id) }}
                                {{ macro.deleteButton( 'realestatecustompage_delete', recp.id) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script src="{{ asset('backend/js/screens/realestatecustompage_list.js') }}"></script>
{% endblock %}

templates/backend/user_list.html.twig
{% extends 'backend/base.html.twig' %}
{% import 'backend/macros/macros.html.twig' as macro %}

{% block title %}{{ "Korisnici"|trans }}{% endblock %}


{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-6">
                    <h6 class="m-0 font-weight-bold text-primary">{{ "Korisnici"|trans }} </h6>
                </div>
                <div class="col-6 text-right">
                    {{ macro.addButton("user_new") }}
                </div>
            </div>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable no-footer dtr-inline" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>{{ "Korisnici"|trans }}</th>
                        <th>{{ "Email"|trans }}</th>
                        <th>{{ "Role"|trans }}</th>
                        <th>{{ "Aktivan"|trans }}</th>
                        <th>{{ "Opcije"|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in userList %}
                        <tr>
                            <td>
                                <div class="btn-circle btn-primary btn-sm margin-right-5"><i class="fas fa-user"></i>
                                </div> {{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                {% for role in user.roles %}
                                    {{ role }}
                                {% endfor %}
                            </td>
                            <td>{% if user.active == 1 %}{{ "DA"|trans }}{% else %}{{ "NE"|trans }}{% endif %}</td>
                            <td>
                                {% if is_granted("ROLE_ADMIN") %}
                                <a href="{{ path('admin_reset_password', {'user_id':  user.id}) }}" class="btn btn-primary btn-circle btn-sm margin-right-5">
                                    <i class="fas fa-key"></i>
                                </a>
                                {% endif %}
                                {{ macro.deleteButton( 'user_delete', user.id) }}
                                {{ macro.editButton( 'user_edit', user.id) }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script src="{{ asset('backend/js/dataTableDefault.js?v=1') }}"></script>
{% endblock %}