src/Entity/RealEstate.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\BaseTrait;
use Oh\GoogleMapFormTypeBundle\Traits\LocationTrait;


/**
 * @ORM\Entity(repositoryClass="App\Repository\RealEstateRepository")
 */
class RealEstate
{
    use BaseTrait {
        BaseTrait::__construct as baseConstruct;
    }

    use LocationTrait;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="realEstates")
     * @ORM\JoinColumn(nullable=false)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\RealEstateType", inversedBy="realEstates")
     * @ORM\JoinColumn(nullable=false)
     */
    private $RealEstateType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Status", inversedBy="realEstates")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $featured;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bedroomCount;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $firstRowByTheSea;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $seaView;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $newBuilding;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $distanceFromTheSea;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $underConstruction;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $pool;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bathroomCount;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $garage;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $fullPrice;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $discountPrice;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $livingArea;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $surfaceArea;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $videoUrl;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $virtualWalkUrl;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $energyClass;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RealEstateFeature", mappedBy="real_estate", orphanRemoval=true, cascade={"persist"})
     */
    private $realEstateFeatures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RealEstateLocalization", mappedBy="RealEstate", orphanRemoval=true, cascade={"persist"})
     */
    private $realEstateLocalizations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RealEstateMetaLocalization", mappedBy="RealEstate", orphanRemoval=true, cascade={"persist"})
     */
    private $realEstateMetaLocalizations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Document", mappedBy="real_estate", orphanRemoval=true, cascade={"persist"})
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity="RealEstateImage", mappedBy="realEstate", orphanRemoval=true, cascade={"persist"})
     */
    private $realEstateImages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GroundPlan", mappedBy="realEstate", orphanRemoval=true, cascade={"persist"})
     */
    private $groundPlans;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="realEstates")
     */
    private $agent;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="clientRealEstates")
     */
    private $client;

    /**
     * @ORM\Column(type="boolean")
     */
    private $priceOnRequest;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $uid;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $administrationNote;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $clientNote;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $keysInPossession;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lotDetails;

    /**
     * @ORM\OneToMany(targetEntity=App\Entity\UserFavorite::class, mappedBy="real_estate")
     */
    private $userFavorites;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $fb_post_id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $twitterPostId;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $immoid;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $immoscout_exported;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $place;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $exportToZoopla;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $zooplaId;

    public function __construct($args)
    {
        $this->baseConstruct();
        $this->realEstateFeatures = new ArrayCollection();
        $this->realEstateLocalizations = new ArrayCollection();
        $this->realEstateMetaLocalizations = new ArrayCollection();
        $this->documents = new ArrayCollection();
        if($args !== null && is_array($args)){

            if(array_key_exists("localizations", $args)) {
                foreach ($args["localizations"] as $localization) {
                    $this->addRealEstateLocalization($localization);
                }
            }
            if(array_key_exists("metaLocalizations", $args)){
                foreach ($args["metaLocalizations"] as $metaLocalization){
                    $this->addRealEstateMetaLocalization($metaLocalization);
                }
            }
        }
        $this->realEstateImages = new ArrayCollection();
        $this->groundPlans = new ArrayCollection();
        $this->userFavorites = new ArrayCollection();
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getRealEstateType(): ?RealEstateType
    {
        return $this->RealEstateType;
    }

    public function setRealEstateType(?RealEstateType $RealEstateType): self
    {
        $this->RealEstateType = $RealEstateType;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBedroomCount(): ?int
    {
        return $this->bedroomCount;
    }

    public function getBedroomCountSafe(): int
    {
        return $this->bedroomCount == null ? 0 : $this->bedroomCount;
    }

    public function setBedroomCount(?int $bedroomCount): self
    {
        $this->bedroomCount = $bedroomCount;

        return $this;
    }

    public function getFirstRowByTheSea(): ?bool
    {
        return $this->firstRowByTheSea;
    }

    public function setFirstRowByTheSea(?bool $firstRowByTheSea): self
    {
        $this->firstRowByTheSea = $firstRowByTheSea;

        return $this;
    }

    public function getSeaView(): ?bool
    {
        return $this->seaView;
    }

    public function setSeaView(?bool $seaView): self
    {
        $this->seaView = $seaView;

        return $this;
    }

    public function getNewBuilding(): ?bool
    {
        return $this->newBuilding;
    }

    public function setNewBuilding(?bool $newBuilding): self
    {
        $this->newBuilding = $newBuilding;

        return $this;
    }

    public function getDistanceFromTheSea(): ?int
    {
        return $this->distanceFromTheSea;
    }

    public function setDistanceFromTheSea(?int $distanceFromTheSea): self
    {
        $this->distanceFromTheSea = $distanceFromTheSea;

        return $this;
    }

    public function getUnderConstruction(): ?bool
    {
        return $this->underConstruction;
    }

    public function setUnderConstruction(?bool $underConstruction): self
    {
        $this->underConstruction = $underConstruction;

        return $this;
    }

    public function getPool(): ?bool
    {
        return $this->pool;
    }

    public function setPool(?bool $pool): self
    {
        $this->pool = $pool;

        return $this;
    }

    public function getBathroomCount(): ?int
    {
        return $this->bathroomCount;
    }

    public function setBathroomCount(?int $bathroomCount): self
    {
        $this->bathroomCount = $bathroomCount;

        return $this;
    }

    public function getGarage(): ?bool
    {
        return $this->garage;
    }

    public function setGarage(?bool $garage): self
    {
        $this->garage = $garage;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getLivingArea(): ?float
    {
        return $this->livingArea;
    }

    public function setLivingArea(float $livingArea): self
    {
        $this->livingArea = $livingArea;

        return $this;
    }

    public function getSurfaceArea(): ?float
    {

src/Controller/Frontend/AgentPageController.php
<?php


namespace App\Controller\Frontend;


use App\Entity\Enum\RealEstateCustomPageTypeEnum;
use App\Entity\Language;
use App\Services\ServiceAgent;
use App\Services\ServiceLanguage;
use App\Services\ServiceLocation;
use App\Services\ServiceRealEstate;
use App\Services\ServiceRealEstateCustomPage;
use Symfony\Component\HttpFoundation\Request;

class AgentPageController extends BaseController
{

    public function index(Request $request, $slug) {
        $serviceAgent = new ServiceAgent($this->em);
        $realEstateService = new ServiceRealEstate($this->em);
        $serviceLocation = new ServiceLocation($this->em);
        $categoryPages = $serviceLocation->getLocationsInOfferLocalized($request->getLocale(), array(RealEstateCustomPageTypeEnum::AUTOGENERATED));

        $serviceLanguage = new ServiceLanguage($this->em);
        $locale = $request->getLocale();
        $language = $serviceLanguage->getByCode($locale);

        $agentPage = $serviceAgent->getAgentPageBySlug($slug, $language);

        //set language selectors
        $languages = $this->em->getRepository(Language::class)->findAll();
        foreach($languages as $language) {
            $newSlug = $serviceAgent->getSlugForLanguage($agentPage["id"], $language->getCode());
            $this->setLanguageSelector($language->getCode(), $this->generateUrl("agentpage", array("slug" => $newSlug, "_locale"=>$language->getCode())));
        }

        $agentRealEstates = $realEstateService->getRealEstatesLocalizedForAgent($agentPage["user_id"], 5, $locale);

        return $this->render("frontend/agentpage.html.twig", array(
            'parameters' => $this->parameters,
            "page" => $agentPage,
            'locationCategoryPages' => $categoryPages,
            'realEstates' => $agentRealEstates
        ));
    }

}

src/Controller/Frontend/BaseController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\CallButton;
use App\Entity\Language;
use App\Form\Frontend\SearchType;
use App\GlobalSettings;
use App\Services\LanguageService;
use App\Services\ServiceExchangeRate;
use App\ViewModel\Frontend\BreadcrumbElementModel;
use App\ViewModel\Frontend\SearchModel;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Services\ContentService;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


abstract class BaseController extends AbstractController
{

    protected $parameters;
    protected $contentService;
    protected $global;
    protected $em;
    protected $session;
    protected $languageService;
    protected $urlGenerator;

    function __construct(ContentService $contentService,SessionInterface $session, GlobalSettings $global, EntityManagerInterface $em, LanguageService $languageService, ServiceExchangeRate $serviceExchangeRate, UrlGeneratorInterface $urlGenerator)
    {
        $this->contentService = $contentService;
        $this->session = $session;
        $this->global = $global;
        $this->languageService = $languageService;
        $this->em = $em;
        $this->parameters = new \stdClass();
        $this->parameters->predefinedContent = $this->contentService->getPredefinedContentSlugs();
        $this->parameters->languages = $this->languageService->getLanguages();
        $this->setMetaDescription($global->getDefaultMetaData()["description"]);
        $this->setMetaTitle($global->getDefaultMetaData()["title"]);
        $this->setLanguageSelector("hr", "/");
        $this->setLanguageSelector("en", "/en");
        $this->setLanguageSelector("de", "/de");
        $this->parameters->callButton = $this->em->getRepository(CallButton::class)->findOneBy(array("active"=> true));

        //Set exchange rate value for easy access in calc of the price in kn
        $currentExchangeRate = $serviceExchangeRate->getCurrentExchangeRate();
        $this->parameters->exchangeRate = $currentExchangeRate != null ? $currentExchangeRate->getRate() : 0;

        $this->urlGenerator = $urlGenerator;
    }

    public function setMetaDescription($text)
    {
        $this->parameters->metaDescription = $text;
    }

    public function addBreadcrumbElement($url, $title)
    {
        $breadcrumb = new BreadcrumbElementModel($title, $url);
        $this->parameters->breadcrumbs[] = $breadcrumb;
    }

    public function setMetaTitle($text)
    {
        $this->parameters->metaTitle = $text;
    }

    public function setLanguageSelector($language, $route)
    {
        $this->parameters->languageSelector[$language] = $route;
    }

    protected function setShowSearchbar(boolean $bShow)
    {
        $this->parameters->showSearchbar = $bShow;
    }

    protected function prepareSearchbarForm($locale)
    {
        $searchModel = new SearchModel();
        $form = $this->createForm(
            SearchType::class,
                $searchModel,
                array(
                    "locale" => $locale,
                    "method" => "GET",
                    "action" => $this->urlGenerator->generate("real_estate_search")
                )
        );

        return $form->createView();
    }
}

src/Controller/Frontend/PredefinedContentController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\CmsPage;
use App\Entity\CmsPageLocalization;
use App\Entity\CmsPageMetaLocalization;
use App\Entity\Enum\RealEstateCustomPageTypeEnum;
use App\Entity\Language;
use App\Services\ContentService;
use App\Services\ServiceLocation;
use App\Services\ServiceRealEstateCustomPage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class PredefinedContentController extends BaseController
{

    public function content(Request $request, TranslatorInterface $translator, $slug)
    {
        $locale = $request->getLocale();
        $cmsPage = $this->contentService->getSingleContent($slug, $locale);
        if(!$cmsPage){
            return $this->render("frontend/error.html.twig", array(
                "message" => $translator->trans("Stranica nije pronađena!"),
                "code" => "404",
                "parameters" => $this->parameters,
                "searchbarForm" => $this->prepareSearchbarForm($locale)
            ));
        }

        $serviceLocation = new ServiceLocation($this->em);
        $categoryPages = $serviceLocation->getLocationsInOfferLocalized($request->getLocale(), array(RealEstateCustomPageTypeEnum::AUTOGENERATED));

        //set language selectors
        $languages = $this->em->getRepository(Language::class)->findAll();
        foreach($languages as $language) {
            $newSlug = $this->contentService->getSingleContentSlug($cmsPage["id"], $language->getCode());
            $this->setLanguageSelector($language->getCode(), $this->generateUrl("predefined_content", array("slug"=>$newSlug, "_locale"=>$language->getCode())));
        }

        //set meta data
        $metaData = $this->contentService->getSingleContentMeta($cmsPage["id"],$request->getLocale());
        $this->setMetaDescription($metaData["description"]);
        $this->setMetaTitle($metaData["title"]);

        return $this->render('frontend/predefined_content.html.twig', [
            'cmsPage' => $cmsPage,
            'parameters' => $this->parameters,
            'locationCategoryPages' => $categoryPages
        ]);
    }
}

templates/frontend/include/content_list_single_item.html.twig
<div class="col-sm-12 col-md-6">
    <a href="{{ path("single_post", {"slug": post.slug}) }}"
       class="pxp-posts-1-item">
        <div class="pxp-posts-1-item-fig-container">
            <div class="pxp-posts-1-item-fig pxp-cover"
                    {% if  post.entity.getCoverPhoto is not null %}
                        style="background-image: url({{ asset("/uploads/img/" ~ post.entity.getCoverPhoto.name) }})"
                    {% endif %}
            ></div>
        </div>
        <div class="pxp-posts-1-item-details">
            <div class="pxp-posts-1-item-details-category">
                {% for category in post.entity.category %}
                    {% if loop.first ==false %},{% endif %}
                    {{ category.getBlogCategoryLocalizations()|filter(c=> c.language.code == app.request.locale)|first.name }}
                {% endfor %}
            </div>
            <div class="pxp-posts-1-item-details-title">{{ post.title }}</div>
            <div class="pxp-posts-1-item-details-date mt-2">{{ post.entity.getCreatedAt()|date("d.m.Y") }}</div>
            <div class="pxp-posts-1-item-cta text-uppercase">{{ "Pročitaj članak"|trans }}</div>
        </div>
    </a>
</div>

templates/frontend/include/gdpr.html.twig
{% set content = parameters.predefinedContent|filter(c => c.display_id == 'cookies-policy')|filter(c=>c.code == app.request.locale) %}
<div id="cookie-msg">
    <div>
    {{ 'Ova web stranica se služi kolačićima'|trans }}. {{ 'Ovdje možete upravljati kolačićima'|trans }}. <br>
    <form id="gdprForm">
        <input type="checkbox"  disabled checked value=1> {{ "kolačići sesije"|trans }}
        <input type="checkbox"  value=2> {{ "analitički kolačići"|trans }}
        <input type="checkbox"  value=3> {{ "marketinški kolačići"|trans }}
    </form>
   {{ "Više o kolačićima možete saznati u našoj"|trans }} <a
            href="{% if content is not empty %}{{ path('predefined_content', {"slug": content|first.slug}) }}{% endif %}">{{ "Politici kolačića"|trans }}<br><br>
        </a>
    <a class="btn-accept-gdpr">{{ "Razumijem"|trans }}</a>
    </div>
</div>

templates/frontend/include/hreflangs.html.twig
{% import 'frontend/macros/macros.html.twig' as macro %}


{% for language in parameters.languages|reverse %}
        <link rel="alternate" href="{{ app.request.getSchemeAndHttpHost()  ~ parameters.languageSelector[language.code] }}" hreflang="{{ language.code}}" />
{% endfor %}

templates/frontend/include/index_search_form_v3.html.twig
    {{ form_start(form, {'attr': {'class': 'pxp-hero-search mt-4 index-filters', "id":"frm-homepage-filters"}}) }}
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="form-group">
                <!-- <input type="text" class="form-control pxp-is-address" placeholder="{{ "Pretraži"|trans ~ "..." }}"> -->
                {{ form_widget(form.text, {"attr": {"class": "form-control pxp-is-address", "placeholder": "Pretraga, lokacija ili ID nekretnine", "autocomplete":"off", "data-reset":"#reset-search-text"}}) }}
                <span class="fa fa-times clear-filter-text d-none" data-target="#search_text" id="reset-search-text"></span>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">

                <div class="form-group">
                    {{ form_widget(form.realEstateType, {"attr": {"class": "form-control form-control-chosen", "data-placeholder": "Svi tipovi nekretnina"|trans}}) }}
                    <span class="fa fa-times clear-select-box d-none" data-target="#search_realEstateType"></span>
                </div>
            </div>

        <div class="col-sm-12 col-md-4">
            <div class="form-group">
                {{ form_widget(form.location, {"attr": {"class": "form-control form-control-chosen", "data-placeholder": "Sve lokacije"|trans}}) }}
                <span class="fa fa-times clear-select-box d-none" data-target="#search_location"></span>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
                <div class="form-group text-center searchbar-price-slider">
                    <input id="price-range-slider" type="text" class="span2" value="" data-slider-min="0"
                           data-slider-max="500001" data-slider-step="50000"
                           data-slider-value="[{{ form.vars.value.priceMin ?? "0" }},{{ form.vars.value.priceMax ?? "500001" }}]"/>
                    <br>
                    €<span id="span-price-min">{{ (form.vars.value.priceMin ?? 0) | number_format(0, ",", ".") }}</span>
                    -
                    €<span id="span-price-max">
                            {% if form.vars.value.priceMax is not null and form.vars.value.priceMax != constant('App\\GlobalSettings::SearchbarPriceSlideMaxValue') %}
                                {{ form.vars.value.priceMax | number_format(0, ",", ".") }}
                            {% else %}
                                {{ ((constant('App\\GlobalSettings::SearchbarPriceSlideMaxValue') - 1) | number_format(0, ",", ".")) ~ "+" }}
                            {% endif %}
                        </span>
                </div>
                <div class="form-group searchbar-price-select">
                    {{ form_widget(form.priceSelector, {"attr": {"class": "form-control form-control-chosen", "data-placeholder": "Sve cijene"|trans}}) }}
                </div>
                {{ form_widget(form.priceMin) }}
                {{ form_widget(form.priceMax) }}

        </div>
    </div>

    <div class="col-sm-12">
        <button type="submit" class="btn btn-labeled btn-primary btn-lg btn-resideo">
            <span class="btn-label"><i class="fa fa-search"></i></span>{{ "Pretraži"|trans }}</button>
    </div>
{{ form_end(form, {"render_rest": false}) }}

templates/frontend/include/language_selector.html.twig
{% import 'frontend/macros/macros.html.twig' as macro %}

<div class="dropdown language-menu">
    <button class="btn btn-link dropdown-toggle language-select" type="button"
            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="true">
        {{ app.request.locale }}
    </button>
    <div class="dropdown-menu language-dropdown-menu" aria-labelledby="dropdownMenuButton">
{% for language in parameters.languages|reverse %}
    {% if language.code != app.request.locale %}

            <a href="{{ parameters.languageSelector[language.code] }}" class="dropdown-item">{{ language.code }}</a>

    {% endif %}
{% endfor %}
</div>
</div>

templates/frontend/include/language_selector_mobile.html.twig
{% import 'frontend/macros/macros.html.twig' as macro %}

{% for language in parameters.languages|reverse %}
    {% if language.code != app.request.locale %}

        <a href="{{ parameters.languageSelector[language.code] }}" class="language-link"><i
                    class="{{ macro.getFlagClass(language.code) }}"></i></a>

    {% endif %}
{% endfor %}

templates/frontend/include/location_category_pages_list_by_type.html.twig
<div class="category-section-front pxp-cover mt-100 pt-5 mb-100 location-category-pages-section"
     style="background-image: url({{ asset("frontend/img/locations_cover_img.jpg") }});"
>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <div>
                    <i class="fa fa-map-marker fa-3x"></i>
                </div>
                <h2 class="pxp-section-h2">{{ viewModel.categoryPage.realEstateCustomPageFilters.realEstateTypes|first.realEstateTypeLocalizations|filter(v=> v.language.code == app.request.locale)|first.titlePrefix|raw ~ " prema lokaciji"|trans }}</h2>
            </div>
        </div>
        <div class="pxp-services-container rounded-lg mt-4 mt-md-5 locations-container">
            <div class="row" style="width: 100%;">
                {% for categoryPage in viewModel.locationCategoryPages %}
                    {% if categoryPage.parentRealEstateCustomPage is not null %}
                        {% set parentLocation = categoryPage.parentRealEstateCustomPage.realEstateCustomPageFilters.locations|first.locationLocalizations|filter(v=> v.language.code == app.request.locale)|first.name %}
                        {% set categoryPageLoc = categoryPage.getRealEstateCustomPageLocalization(app.request.locale) %}
                        {% if  categoryPageLoc is not  null %}
                            {% set parentLoc = categoryPage.parentRealEstateCustomPage.getRealEstateCustomPageLocalization(app.request.locale) %}
                            {% if  parentLoc is not null %}
                                <div class="col-6 col-sm-6 col-md-4 col-lg-3 padding-5">
                                    <a href="{{ path('category_page', {'slugCategory': parentLoc.slug , 'slugSubCategory': categoryPageLoc.slug}) }}"
                                       class="pxp-category-link text-uppercase mt-1 mt-md-4 "
                                    >
                                        <i class="fa fa-circle"></i>
                                        {{ parentLocation }}
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

</div>

templates/frontend/include/location_category_pages_list_v2.html.twig
<div class="category-section-front pxp-cover mt-100 pt-5 mb-100 location-category-pages-section lazy"
     data-src="{{ asset("frontend/img/locations_cover_img.jpg") }}"
>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <div>
                    <i class="fa fa-map-marker fa-3x"></i>
                </div>
                <h2 class="pxp-section-h2">{{ "Ponuda nekretnina prema lokaciji" | trans }}</h2>
            </div>
        </div>
        <div class="pxp-services-container rounded-lg mt-4 mt-md-5 locations-container">
            <div class="row">
                {% for categoryPage in locationCategoryPages %}
                    <div class="col-6 col-sm-6 col-md-4 col-lg-3 padding-5" >
                        <a href="{{ path('category_page', {'slugCategory': categoryPage.slug}) }}"
                           class="pxp-category-link text-uppercase mt-1 mt-md-4 "
                        >
                            <i class="fa fa-circle"></i>
                            {{ categoryPage.location_name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>

templates/frontend/include/login_form.html.twig
<div class="text-center">
    <h2 class="h4 text-gray-900 mb-4">{{ "Dobrodošli"|trans }}!</h2>
</div>
{% if loginError is defined%}
    <div style="color:#ff0000;padding-bottom:10px;">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
{% endif %}
<form action="{{ path('login') }}" method="post">
    <div class="form-group">
        <input type="email" class="form-control" placeholder="{{"unesi"|trans ~ " " ~ "email"|trans}}" id="email" name="_email"
               value="{% if last_username is defined %}{{ last_username }}{% endif %}"/>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="{{"unesi"|trans ~ " " ~ "password"|trans}}" id="password"
               name="_password"/>
    </div>

    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />
    <button type="submit" class="btn btn-primary btn-block">{{ "prijava"|trans }}</button>
</form>
<hr>

<div class="form-group mt-4 text-center pxp-modal-small">
    <a href="{{ path("forgot_password") }}"
       class="pxp-modal-link">{{ "Zaboravljena lozinka"|trans }}</a>
</div>
<div class="text-center pxp-modal-small">
    <a href="{{ path("registration") }}"
       class="pxp-modal-link">{{ "Novi račun"|trans }}</a>
</div>